theme: jekyll-theme-minimal
title: Brittle Opacity
description: Disnovation.org (Nicolas Maigret and Maria Roszkowska), Predictive Art Bot V3 (2017). Photo\:\ Gabriel Asper, CC NC-SA 4.0.
logo: https://github.com/dejangrba/brittle-opacity/predictive-art-bot-v3_35243296642_o-1000px.png
